name: "Control Plane Deploy"
on:
  push:
    branches:
      - "main"
jobs:
  deploy-control-plane:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: npm ci
      - run: npm run cdk deploy -- --require-approval=never --app "npx ts-node --prefer-ts-exts bin/control-plane.app.ts"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_WORKFLOW_URL: ${{ secrets.GH_WORKFLOW_URL }}
          DATA_PLANE_ACCOUNTS: ${{ secrets.DATA_PLANE_ACCOUNTS }}
          ORG_ID: ${{ secrets.ORG_ID }}
      - name: Install UI
        working-directory: ./src/control-plane/ui/app
        run: npm ci
      - name: Build UI
        working-directory: ./src/control-plane/ui/app
        run: npm run build && npm run export
      - name: Deploy UI
        uses: ./.github/actions/deploy-paas
        worrking-directory: ./src/control-plane/ui/app
        with:
          applicationName: test-app
          distributionDirectory: out
