on:
  workflow_dispatch:
    inputs:
      customerId:
        description: "Customer ID"
        required: true
      applicationId:
        description: "Application ID"
        required: true
      region:
        description: "Region to deploy"
        required: true
      sourceFilesZipName:
        description: "Source files Zip Name"
        required: false
jobs:
  deploy-data-plane:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/checkout@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.region }}
      - run: npm ci
      - run: npm run cdk deploy -- --require-approval=never --app "npx ts-node --prefer-ts-exts bin/data-plane.app.ts" --context customerId=${{ inputs.customerId }} --context applicationId=${{ inputs.applicationId }} --context sourceFilesZipName=${{ inputs.sourceFilesZipName }}
